export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const TOGGLE_AUTH_MODAL = 'TOGGLE_AUTH_MODAL';
export const SET_AUTH_MODAL_MODE = 'SET_AUTH_MODAL_MODE';
export const SET_ADS_CATEGORIES = 'SET_ADS_CATEGORIES';
export const SET_MODAL_PHOTO = 'SET_MODAL_PHOTO';