// user ads list
export const SET_USER_ADS = 'SET_USER_ADS';
export const TOGGLE_IS_LOAD_USER_ADS = 'TOGGLE_IS_LOAD_USER_ADS';

// edit ad
export const TOGGLE_IS_LOAD_EDIT_AD_DATA = 'TOGGLE_IS_LOAD_EDIT_AD_DATA';
export const SET_EDIT_AD_DATA = 'SET_EDIT_AD_DATA';

export const EDIT_AD_CHANGE_TYPE_ID = 'EDIT_AD_CHANGE_TYPE_ID';
export const EDIT_AD_CHANGE_TITLE = 'EDIT_AD_CHANGE_TITLE';
export const EDIT_AD_CHANGE_DESCRIPTION = 'EDIT_AD_CHANGE_DESCRIPTION';
export const EDIT_AD_CHANGE_CATEGORY_ID = 'EDIT_AD_CHANGE_CATEGORY_ID';
export const EDIT_AD_CHANGE_POINT = 'EDIT_AD_CHANGE_POINT';
export const EDIT_AD_CHANGE_ADDRESS = 'EDIT_AD_CHANGE_ADDRESS';
export const EDIT_AD_CHANGE_SECRET_QUESTION = 'EDIT_AD_CHANGE_SECRET_QUESTION';
export const EDIT_AD_CHANGE_SECRET_ANSWER = 'EDIT_AD_CHANGE_SECRET_ANSWER';
export const EDIT_AD_CHANGE_LOST_OR_FOUND_AT = 'EDIT_AD_CHANGE_LOST_OR_FOUND_AT';

export const EDIT_AD_SET_ERROR_MESSAGE = 'EDIT_AD_SET_ERROR_MESSAGE';
export const EDIT_AD_TOGGLE_LOAD_SUBMIT_EDIT_AD = 'IS_LOAD_SUBMIT_EDIT_AD';
export const EDIT_AD_SET_INFO_MODAL_MESSAGE = 'EDIT_AD_SET_INFO_MODAL_MESSAGE';

// answers
export const TOGGLE_IS_LOAD_ANSWERS = 'TOGGLE_IS_LOAD_ANSWERS';
export const SET_ANSWERS = 'SET_ANSWERS';

