export const SET_FOUND_ADS = 'SET_FOUND_ADS';
export const CHANGE_CURRENT_PAGE = 'CHANGE_CURRENT_PAGE';
export const TOGGLE_IS_LOAD_RESULTS = 'TOGGLE_IS_LOAD_RESULTS';

export const SET_SEARCH_PARAMS = 'SET_SEARCH_PARAMS';

export const CHANGE_WORD_SEARCH_QUERY = 'CHANGE_WORD_SEARCH_QUERY';
export const CHANGE_NOVELTY_ORDER_SEARCH_QUERY = 'CHANGE_NOVELTY_ORDER_SEARCH_QUERY';
export const CHANGE_TYPE_AD_SEARCH_QUERY = 'CHANGE_TYPE_AD_SEARCH_QUERY';
export const CHANGE_CATEGORY_SEARCH_QUERY = 'CHANGE_CATEGORY_SEARCH_QUERY';
export const CHANGE_ADDRESS_SEARCH_QUERY = 'CHANGE_ADDRESS_SEARCH_QUERY';
